- name: Ensure docker postgres directories exist
  become: true
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_postgres_data_dir }}"
  tags:
    - install
    - upgrade


- name: Run docker postgres container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_postgres_env }}"
    expose: "{{ docker_postgres_expose }}"
    image: "{{ docker_postgres_image }}"
    links: "{{ docker_postgres_links }}"
    volumes: "{{ docker_postgres_volumes }}"
    memory_limit: "{{ docker_postgres_memory_limit }}"
    name: "{{ docker_postgres_name }}"
    ports: "{{ docker_postgres_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_postgres_volumes }}"
  tags:
    - install
    - upgrade
